baseURL = ""
languageCode = "en-us"
title = "Codescapade"
relativeurls = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[params]
  dateFormat = "Jan 2, 2006"
  env = "dev"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Games"
    url = "/games/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5