baseURL = ""
languageCode = "en-us"
title = "Codescapade"
relativeurls = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[params]
  dateFormat = "Jan 2, 2006"
  env = "production"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "<i data-feather=\"home\" class=\"feather-icon\"></i>"

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
    pre = "<i data-feather=\"book-open\" class=\"feather-icon\"></i>"

  [[menu.main]]
    name = "Games"
    url = "/games/"
    weight = 3
    pre = "<i class=\"material-icons-outlined mobile-nav\">videogame_asset</i>"

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
    pre = "<i class=\"material-icons-outlined mobile-nav\">info</i>"
